// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqi2_hzsSxLaxL3eIdHM4uLqxU3zBsuD8',
    appId: '1:996789373458:web:1ea9f53e9c2c64a46466cb',
    messagingSenderId: '996789373458',
    projectId: 'pioneerbible-3e556',
    authDomain: 'pioneerbible-3e556.firebaseapp.com',
    storageBucket: 'pioneerbible-3e556.firebasestorage.app',
    measurementId: 'G-M92ZJGKH5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7Hs3eL_n0dsevnZBcqWiOianDpYMovs',
    appId: '1:996789373458:android:0dc7eb24e1c5819e6466cb',
    messagingSenderId: '996789373458',
    projectId: 'pioneerbible-3e556',
    storageBucket: 'pioneerbible-3e556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxsrPB03TPMVtY5-VippHCedTGV-O2Dw',
    appId: '1:996789373458:ios:18beb506a6cddb456466cb',
    messagingSenderId: '996789373458',
    projectId: 'pioneerbible-3e556',
    storageBucket: 'pioneerbible-3e556.firebasestorage.app',
    iosBundleId: 'com.example.flutterSeniorProjectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATxsrPB03TPMVtY5-VippHCedTGV-O2Dw',
    appId: '1:996789373458:ios:b608ffeffc72bae86466cb',
    messagingSenderId: '996789373458',
    projectId: 'pioneerbible-3e556',
    storageBucket: 'pioneerbible-3e556.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqi2_hzsSxLaxL3eIdHM4uLqxU3zBsuD8',
    appId: '1:996789373458:web:b17d27809c2746a96466cb',
    messagingSenderId: '996789373458',
    projectId: 'pioneerbible-3e556',
    authDomain: 'pioneerbible-3e556.firebaseapp.com',
    storageBucket: 'pioneerbible-3e556.firebasestorage.app',
    measurementId: 'G-QCMSJ8Z2LM',
  );

}